export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER = "SET_USER";
export const LOGOUT_USER = "LOGOUT_USER";

export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_THE_USER = "REGISTER_THE_USER";

export const SET_LISTS = "SET_LISTS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPLOAD_THE_PRODUCT = "UPLOAD_THE_PRODUCT";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_ONE_PRODUCT = "GET_ONE_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_THAT_PRODUCT = "GET_THAT_PRODUCT";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const DELETE_ONE_PRODUCT = "DELETE_ONE_PRODUCT";
export const UPDATE_THIS_PRODUCT = "UPDATE_THIS_PRODUCT";

export const INCREMENT_ITEM = "INCREMENT_ITEM";

export const CART_ITEM = "CART_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const SET_PRICE = "SET_PRICE";
export const PLACE_ORDER = "PLACE_ORDER";
